server:
  port: 31001
spring:
  application:
    name: xc-service-mange-cmss
  freemarker:
    cache: false  #关闭模板缓存，方便测试
    settings:
      template_update_delay: 0 #检查模板更新延迟时间，设置为0表示立即检查，如果时间大于0会有缓存不方便进行模板测试
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: xc_cms
